# This is a sample config.toml document for EOSIO DSPs

[dsp]
# enter account
account = "<DSP ACCOUNT>"
# enter account private key
private_key = "<DSP PRIVATE KEY>"
port = 3115
# configure available services: (comment for all services)
# services_enabled = "ipfs,log,vaccounts,oracle,cron,readfn,auth,storage,history,sign"
# account_permissions = "active"
# consumer_pays: setting this to true forces consumer to pay for all cpu/net/ram
# however, if they don't have the correct permission setup, everything will fail
# review consumer pays documentation prior to setting this to true
consumer_pays = false

[database]
# url syntax: postgres://user:pass@example.com:5432/dbname
url = "postgres://user:pass@example.com:5432/dbname"

# production (uses above url for database)
node_env = "production"

[nodeos]
host = "localhost"
port = 8888
secured = false

# mainnet:
chainid = "aca376f206b8fc25a6ed44dbdc66547c36c6c33e3a119ffbeaef943642f0e906"
# kylin: "5fff1dae8dc8e2fc4d5b23b2c7665c97f9e9d8edf2b6485a86ba311c25639191"

# if using state_history_plugin: 
websocket_port = 8887

[demux]
socket_mode = "sub"
# head block to sync demux from
head_block = 35000000
# demux defaults to first pulling head block from toml file if postgres database is not set
# after database is set, defaults to databse, to overwrite and default to toml file, pass true
bypass_database_head_block = false

[ipfs]
protocol = "http"
host = "localhost"
port = 5001

# sidechain section, if no sidechains, leave as [sidechains], can add additional sidechains with [sidechains.newchain] ...
[sidechains]
  [sidechains.test1]
    # dsp
    dsp_port = 3116 # dsp port to run new chain's services on, this is the port developers will push to, must be unique per new chain
    dsp_account = "test1" # DSP Account on new chain
    dsp_private_key = "" # DSP active private key on new chain
    # nodeos
    nodeos_host = "localhost" # nodeos host running new chain
    nodeos_port = 8888 # nodeos host port
    nodeos_secured = false # nodeos secured bool (true: https, false: http)
    nodeos_chainid = "" # chainid of new chain
    nodeos_websocket_port = 8887 # nodeos websocket port, can be same per nodeos instance
    webhook_dapp_port = 8113 # nodeos webhook port, must be unique per chain
    # demux
    demux_webhook_port = 3196 # port demux runs on, must be unique per new chain
    demux_socket_mode = "sub"
    demux_head_block = 1
    # demux defaults to first pulling head block from toml file if postgres database is not set
    # after database is set, defaults to database, to overwrite and default to toml file, pass true
    demux_bypass_database_head_block = false
    # sidechain 
    liquidx_contract = "liquidx.dsp" # liquidx contract on the EOS mainnet
    name = "test1" # CHAIN_NAME - contract on the EOS mainnet that registered the new chain
    # the mapping below contains the dappservices:dappservicex and mainnet DSP account to the new chain's DSP account mapping
    mapping = "dappservices:dappservicex,heliosselene:heliosselene"
  # [sidechains.ANOTHER_CHAIN_NAME]
    # ...
